import Sidebar from "@/components/layout/Sidebar";
import "./globals.css";
import Particles from "@/components/background/Particals";
import ClientProvider from "@/components/ClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="fixed inset-0 -z-10">
          <Particles
            particleColors={['#FAFAFA', '#FAFAFA']}
            particleCount={200}
            particleSpread={10}
            speed={0.1}
            particleBaseSize={100}
            moveParticlesOnHover
            alphaParticles={false}
            disableRotation={false}
          />
        </div>

        <ClientProvider>
          <div className="relative z-10 md:ml-16">
            <Sidebar />
            {children}
          </div>
        </ClientProvider>
      </body>
    </html>
  );
}
